services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ppguser
      POSTGRES_PASSWORD: ppgpass
      POSTGRES_DB: ppgdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ppguser -d ppgdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env        # tüm hassas bilgiler buradan gelir
    environment:
      DATABASE_URL: postgresql+psycopg://ppguser:ppgpass@db:5432/ppgdb
    volumes:
      - ./backend:/app
      - ./ml_models:/app/../ml_models
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  pgdata:
